

GRANT SELECT ON PROYECTOABD_ER.CLIENTE TO PROYECTOABD_DW;
GRANT SELECT ON PROYECTOABD_ER.ORDEN_COMPRA TO PROYECTOABD_DW;
GRANT SELECT ON PROYECTOABD_ER.PRODUCTO TO PROYECTOABD_DW;
GRANT SELECT ON PROYECTOABD_ER.TIPO_ENVIO TO PROYECTOABD_DW;
GRANT SELECT ON PROYECTOABD_ER.TIPO_PRODUCTO TO PROYECTOABD_DW;
--------------------------------------------------------------------------------
GRANT SELECT, INSERT ON PROYECTOABD_SA.SA_CLIENTE TO PROYECTOABD_DW;
GRANT SELECT, INSERT ON PROYECTOABD_SA.SA_ORDEN_COMPRA TO PROYECTOABD_DW;
GRANT SELECT, INSERT ON PROYECTOABD_SA.SA_PRODUCTO TO PROYECTOABD_DW;
GRANT SELECT, INSERT ON PROYECTOABD_SA.SA_TIPO_ENVIO TO PROYECTOABD_DW;
GRANT SELECT, INSERT ON PROYECTOABD_SA.SA_TIPO_PRODUCTO TO PROYECTOABD_DW;
